# Generated by Django 4.2.8 on 2025-04-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_at_task_is_complete_task_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
